# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI

## Trigger the workflow on any push to the main branch or pull request. 
## Push and Pull are two different trigger or event.
## we can have so many branches 

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main


## runs-on  serves as a container: , jobs will run on some type of container like ubuntu

jobs:
  test:
    runs-on: ubuntu-latest

    ## workflow steps :

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run tests
        run: pytest
